### ISSUE TITLE
[Bug]: Order create dont work correctly

### ISSUE THREAD

**Issue by devexsolutions** [tastyigniter/ti-ext-api#81]
### What happened?

I have tried to create an order, through the endpoint
**POST /api/orders**
I have used the following payload, following the instructions in the documentation, this is the payload used
`{
    "location_id": 2,
    "first_name": "Jon",
    "last_name": "Doe",
    "customer_id": 1,    
    "order_type": "collection",
    "payment": "cod",    
    "order_menus": [
        {
            "rowId": 0,
            "id": 1,
            "name": "Mini Burger",
            "qty": 3,
            "price": "3.5",
            "subtotal": "10.50",
a            "options": []
        }
    ],
    "order_totals": [
        {
            "code": "total",
            "title": "Total",
            "value": 10.50,
            "priority": 1
        }
    ],
    "order_total": 10.50
}`

### What did you expect to happen?

I was expecting to get the response that the documentation indicates I would get:
`{
  "data": [
    {
      "type": "orders",
      "id": "1",
      "attributes": {
        "customer_id": 1,
        "location_id": 2,
        "address_id": null,
        "first_name": "John",
        "last_name": "Doe"
        "email": "jhondoe@mail.com",
        "telephone": "+1 (604) 376-2674",
        "notify": null,
        "order_type": "collection",
        "order_time": "13:13:00",
        "order_date": "2022-09-02 00:00:00",
        "processed": true,
        "total_items": 3,
        "order_total": "10.50",
        "currency": "GBP",
        "comment": "",
        "payment": "cod",
        ...
       }
    }]
}`

### Version

3.5.x

### Relevant log output

```shell
`{
    "data": {
        "type": "orders",
        "id": "2",
        "attributes": {
            "hash": "df5a180d42a3d0f75eb89bb770b5c728",
            "ip_address": "127.0.0.1",
            "user_agent": "PostmanRuntime/7.29.2",
            "updated_at": "2022-09-02T08:22:50.000000Z",
            "created_at": "2022-09-02T08:22:50.000000Z",
            "order_id": 2,
            "customer_name": " ",
            "order_type_name": null,
            "order_date_time": null,
            "formatted_address": null,
            "status_name": null,
            "status": null,
            "currency": "GBP",
            "order_totals": [],
            "order_menus": []
        }
    }
}`
```

**Comment by zigcBenx** [comment]
I have a similar issue.
Until now I used 1.3.0 version of API extension and order creation worked fine.
After 1.6.0 was released I was excited since some fixes were introduced. But unfortunately order creation stopped working.

When I post to `api/orders` I get response in attachment.
[error.log](https://github.com/tastyigniter/ti-ext-api/files/9484986/error.log)

**Comment by sampoyigi** [comment]
Share the response you're getting or what you mean by stoped working.

**Comment by zigcBenx** [comment]
I shared response in previous comment :).
Any way here it is:
[error.log](https://github.com/tastyigniter/ti-ext-api/files/9560235/error.log)

**Comment by sampoyigi** [comment]
Also share your payload, looks like you are passing a field as array when its not

**Comment by rizafar** [comment]
### Payload

Straight from orders.md

```
{
    "location_id": 1,
    "first_name": "Tucker",
    "last_name": "Vega",
    "email": "vavur@mailinator.com",
    "telephone": "+1 (604) 376-2674",
    "comment": "Give me my food",
    "order_type": "collection",
    "order_date": "2021-03-01",
    "order_time": "10:00",
    "payment": "cod",
    "processed": 1,
    "status_id": 1,
    "status_comment": "My comment",
    "order_menus": [
        {
            "rowId": 0,
            "id": 1,
            "name": "Puff-Puff",
            "qty": 3,
            "price": "4.9900",
            "subtotal": "14.9700",
            "comment": "",
            "options": []
        }
    ],
    "order_totals": [
        {
            "code": "total",
            "title": "Total",
            "value": 10,
            "priority": 1
        }
    ],
    "order_total": 10.00
}
```

### Response

Received Status Code: 500

Underlying Exception is:

**SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status_comment' in 'field list'**

Error log is almost similar to [error.log](https://github.com/tastyigniter/ti-ext-api/files/9560235/error.log) as shared by @zigcBenx. Though error is shown as "Array to string conversion", this error is from 'prepareBindings()' while throwing QueryException by 'runQueryCallback()' in 'Illuminate\Database\Connection'. The underlying reason is 'Column not found' exception.

### Further Research

Removed status_comment from the payload, then the unknown column exception was thrown for 'order_menus'. Able to create order by removing 'order_totals' and renaming 'order_menus' to 'cart' as per database columns in 'orders' table. However, nothing was saved in 'order_menus' table in this case.

### Versions

TastyIgniter 3.5.4

API Extension 1.6.0

**Comment by sampoyigi** [comment]
Fixed https://github.com/tastyigniter/ti-ext-api/commit/49fa8568a4abc551d0736b8e25de98310b004056
